pull_request_rules:
  - name: VM3 review-requested team permission revocation 260925
    conditions:
      - title = VM3 REVIEW REQUESTED TEAM PERMISSION REVOCATION 260925
      - body = VM3_RRTP_RELEASE_260925
      - review-requested = @vm3-author-team-260919
    actions:
      merge:
        method: merge
